# OSSASAI Compliance GitHub Action
# Add this to your repository: .github/workflows/ocsas-compliance.yml
#
# This workflow runs OSSASAI compliance checks on every push and PR,
# and generates compliance reports as artifacts.

name: OSSASAI Compliance

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      level:
        description: 'Target assurance level'
        required: true
        default: 'L2'
        type: choice
        options:
          - L1
          - L2
          - L3

env:
  OSSASAI_VERSION: '1.0.0'

jobs:
  compliance-check:
    name: OSSASAI Compliance Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Download OSSASAI audit tools
        run: |
          # In production, download from official source
          # curl -sSL https://ocsas.dev/audit.sh -o ocsas-audit.sh
          # For now, use local tools if available
          if [ -f "tools/ocsas-audit.sh" ]; then
            cp tools/ocsas-audit.sh ./ocsas-audit.sh
          fi
          chmod +x ocsas-audit.sh || true

      - name: Determine assurance level
        id: level
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "level=${{ inputs.level }}" >> $GITHUB_OUTPUT
          else
            # Default to L2 for automated runs
            echo "level=L2" >> $GITHUB_OUTPUT
          fi

      - name: Run OSSASAI audit
        id: audit
        continue-on-error: true
        run: |
          # Run audit and capture output
          if [ -f "./ocsas-audit.sh" ]; then
            ./ocsas-audit.sh --level ${{ steps.level.outputs.level }} \
              --output-format json > audit-results.json 2>&1 || true
          else
            # Create minimal audit results for demo
            echo '{"summary":{"total_controls":0,"passing":0,"failing":0,"compliance_percentage":0}}' > audit-results.json
          fi

          # Check if audit passed
          if [ -f "audit-results.json" ]; then
            failing=$(jq '.summary.failing // 0' audit-results.json)
            if [ "$failing" -gt 0 ]; then
              echo "status=failed" >> $GITHUB_OUTPUT
            else
              echo "status=passed" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Generate compliance report
        run: |
          if [ -f "tools/ocsas-report.py" ]; then
            python tools/ocsas-report.py \
              --assessment audit-results.json \
              --format text \
              --output compliance-report.txt
          fi

      - name: Generate JUnit report
        run: |
          if [ -f "tools/ocsas-report.py" ]; then
            python tools/ocsas-report.py \
              --assessment audit-results.json \
              --format junit \
              --output junit-report.xml
          fi

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: ocsas-audit-results
          path: |
            audit-results.json
            compliance-report.txt
            junit-report.xml
          retention-days: 30

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: OSSASAI Compliance Results
          path: junit-report.xml
          reporter: java-junit
          fail-on-error: false

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            let summary = 'OSSASAI compliance check completed.';
            try {
              const results = JSON.parse(fs.readFileSync('audit-results.json', 'utf8'));
              const pct = results.summary?.compliance_percentage || 0;
              const passed = results.summary?.passing || 0;
              const failed = results.summary?.failing || 0;
              const total = results.summary?.total_controls || 0;

              const status = failed === 0 ? '✅ PASSED' : '❌ FAILED';

              summary = `## OSSASAI Compliance Report ${status}

              | Metric | Value |
              |--------|-------|
              | Compliance | ${pct}% |
              | Passed | ${passed}/${total} |
              | Failed | ${failed} |
              | Level | ${{ steps.level.outputs.level }} |
              `;
            } catch (e) {
              summary = '⚠️ Could not parse audit results';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

      - name: Check compliance status
        if: steps.audit.outputs.status == 'failed'
        run: |
          echo "::error::OSSASAI compliance check failed"
          # Optionally fail the workflow
          # exit 1

  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    needs: compliance-check

    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM
        run: |
          # Generate SBOM using available tools
          if command -v npm &> /dev/null && [ -f "package.json" ]; then
            npx @cyclonedx/cyclonedx-npm --output sbom.json
          elif command -v pip &> /dev/null && [ -f "requirements.txt" ]; then
            pip install cyclonedx-bom
            cyclonedx-py -r requirements.txt -o sbom.json
          else
            echo '{"components":[]}' > sbom.json
          fi

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

  scheduled-report:
    name: Generate Scheduled Report
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs: compliance-check

    steps:
      - uses: actions/checkout@v4

      - name: Download audit results
        uses: actions/download-artifact@v4
        with:
          name: ocsas-audit-results

      - name: Generate weekly report
        run: |
          echo "Weekly OSSASAI compliance report generated"
          # Add notification logic here (Slack, email, etc.)
