# OSSASAI Compliance GitHub Action
# Add this to your repository: .github/workflows/ossasai-compliance.yml
#
# This workflow runs OSSASAI compliance checks on every push and PR,
# and generates compliance reports as artifacts.

name: OSSASAI Compliance

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      level:
        description: 'Target assurance level'
        required: true
        default: 'L2'
        type: choice
        options:
          - L1
          - L2
          - L3

env:
  OSSASAI_VERSION: '2.0.0'

jobs:
  compliance-check:
    name: OSSASAI Compliance Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    outputs:
      status: ${{ steps.audit.outputs.status }}
      compliance: ${{ steps.audit.outputs.compliance }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Locate OSSASAI audit tools
        id: tools
        run: |
          # Check for local tools first
          if [ -f "tools/ossasai-audit.sh" ]; then
            echo "audit_script=tools/ossasai-audit.sh" >> $GITHUB_OUTPUT
            echo "report_script=tools/ossasai-report.py" >> $GITHUB_OUTPUT
            chmod +x tools/ossasai-audit.sh
          elif [ -f "ossasai-audit.sh" ]; then
            echo "audit_script=./ossasai-audit.sh" >> $GITHUB_OUTPUT
            echo "report_script=./ossasai-report.py" >> $GITHUB_OUTPUT
            chmod +x ossasai-audit.sh
          else
            echo "::error::OSSASAI audit tools not found"
            echo "audit_script=" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Determine assurance level
        id: level
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "level=${{ inputs.level }}" >> $GITHUB_OUTPUT
          else
            # Default to L2 for automated runs
            echo "level=L2" >> $GITHUB_OUTPUT
          fi

      - name: Run OSSASAI audit
        id: audit
        run: |
          AUDIT_SCRIPT="${{ steps.tools.outputs.audit_script }}"

          if [ -z "$AUDIT_SCRIPT" ] || [ ! -f "$AUDIT_SCRIPT" ]; then
            echo "::error::Audit script not available"
            echo "status=error" >> $GITHUB_OUTPUT
            echo "compliance=0" >> $GITHUB_OUTPUT
            exit 1
          fi

          # Run audit - capture exit code properly
          set +e
          "$AUDIT_SCRIPT" --level ${{ steps.level.outputs.level }} \
            --output-format json > audit-results.json 2>&1
          AUDIT_EXIT=$?
          set -e

          # Validate output is valid JSON
          if ! jq empty audit-results.json 2>/dev/null; then
            echo "::error::Audit produced invalid JSON output"
            cat audit-results.json
            echo "status=error" >> $GITHUB_OUTPUT
            echo "compliance=0" >> $GITHUB_OUTPUT
            exit 1
          fi

          # Extract results
          failing=$(jq -r '.summary.failing // 0' audit-results.json)
          compliance=$(jq -r '.summary.compliance_percentage // 0' audit-results.json)

          echo "compliance=$compliance" >> $GITHUB_OUTPUT

          if [ "$failing" -gt 0 ]; then
            echo "status=failed" >> $GITHUB_OUTPUT
            echo "::warning::OSSASAI compliance check found $failing failing controls"
          else
            echo "status=passed" >> $GITHUB_OUTPUT
            echo "OSSASAI compliance check passed"
          fi

      - name: Generate text report
        if: always() && steps.tools.outputs.report_script != ''
        run: |
          REPORT_SCRIPT="${{ steps.tools.outputs.report_script }}"
          if [ -f "$REPORT_SCRIPT" ] && [ -f "audit-results.json" ]; then
            python "$REPORT_SCRIPT" \
              --assessment audit-results.json \
              --format text \
              --output compliance-report.txt
          fi

      - name: Generate JUnit report
        if: always() && steps.tools.outputs.report_script != ''
        run: |
          REPORT_SCRIPT="${{ steps.tools.outputs.report_script }}"
          if [ -f "$REPORT_SCRIPT" ] && [ -f "audit-results.json" ]; then
            python "$REPORT_SCRIPT" \
              --assessment audit-results.json \
              --format junit \
              --output junit-report.xml
          fi

      - name: Generate YAML compliance statement
        if: always() && steps.tools.outputs.report_script != ''
        run: |
          REPORT_SCRIPT="${{ steps.tools.outputs.report_script }}"
          if [ -f "$REPORT_SCRIPT" ] && [ -f "audit-results.json" ]; then
            python "$REPORT_SCRIPT" \
              --assessment audit-results.json \
              --format yaml \
              --output compliance-statement.yaml
          fi

      - name: Upload audit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ossasai-audit-results
          path: |
            audit-results.json
            compliance-report.txt
            compliance-statement.yaml
            junit-report.xml
          retention-days: 90
          if-no-files-found: warn

      - name: Publish test results
        if: always() && hashFiles('junit-report.xml') != ''
        uses: dorny/test-reporter@v1
        with:
          name: OSSASAI Compliance Results
          path: junit-report.xml
          reporter: java-junit
          fail-on-error: true

      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const status = '${{ steps.audit.outputs.status }}';
            const level = '${{ steps.level.outputs.level }}';
            let summary = '';

            try {
              if (fs.existsSync('audit-results.json')) {
                const results = JSON.parse(fs.readFileSync('audit-results.json', 'utf8'));
                const pct = results.summary?.compliance_percentage || 0;
                const passed = results.summary?.passing || 0;
                const failed = results.summary?.failing || 0;
                const skipped = results.summary?.skipped || 0;
                const total = results.summary?.total_controls || 0;
                const applicable = results.summary?.applicable || total;

                const statusEmoji = failed === 0 ? '✅' : '❌';
                const statusText = failed === 0 ? 'PASSED' : 'FAILED';

                summary = `## ${statusEmoji} OSSASAI Compliance Report - ${statusText}

            **Target Level:** ${level}

            | Metric | Value |
            |--------|-------|
            | Compliance | ${pct}% |
            | Passed | ${passed}/${applicable} |
            | Failed | ${failed} |
            | Skipped | ${skipped} |

            <details>
            <summary>View full report</summary>

            Download the compliance report artifact for detailed findings.

            </details>
            `;
              } else {
                summary = `## ⚠️ OSSASAI Compliance Report - Error

            Could not generate compliance report. Check the workflow logs for details.
            `;
              }
            } catch (e) {
              summary = `## ⚠️ OSSASAI Compliance Report - Error

            Error parsing audit results: ${e.message}
            `;
            }

            // Check for existing comment to update
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const botComment = comments.find(c =>
              c.user.type === 'Bot' &&
              c.body.includes('OSSASAI Compliance Report')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: summary
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: summary
              });
            }

      - name: Enforce compliance
        if: steps.audit.outputs.status == 'failed'
        run: |
          echo "::error::OSSASAI compliance check failed for level ${{ steps.level.outputs.level }}"
          echo ""
          echo "Review the compliance report artifact for details on failing controls."
          echo "Run locally with: ./tools/ossasai-audit.sh --level ${{ steps.level.outputs.level }} --verbose"
          exit 1

  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    needs: compliance-check
    if: always() && needs.compliance-check.result != 'cancelled'

    steps:
      - uses: actions/checkout@v4

      - name: Generate SBOM
        id: sbom
        run: |
          SBOM_GENERATED=false

          # Try npm
          if [ -f "package.json" ] && command -v npm &> /dev/null; then
            npm install -g @cyclonedx/cyclonedx-npm 2>/dev/null || true
            if command -v cyclonedx-npm &> /dev/null; then
              cyclonedx-npm --output sbom.json && SBOM_GENERATED=true
            fi
          fi

          # Try pip
          if [ "$SBOM_GENERATED" != "true" ] && [ -f "requirements.txt" ]; then
            pip install cyclonedx-bom 2>/dev/null || true
            if command -v cyclonedx-py &> /dev/null; then
              cyclonedx-py -r requirements.txt -o sbom.json && SBOM_GENERATED=true
            fi
          fi

          # Create minimal SBOM if nothing else worked
          if [ "$SBOM_GENERATED" != "true" ]; then
            echo "::warning::Could not generate SBOM - no supported package manager found"
            echo '{"bomFormat":"CycloneDX","specVersion":"1.4","version":1,"components":[]}' > sbom.json
          fi

          echo "generated=$SBOM_GENERATED" >> $GITHUB_OUTPUT

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          retention-days: 90

  scheduled-report:
    name: Generate Scheduled Report
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs: compliance-check

    steps:
      - uses: actions/checkout@v4

      - name: Download audit results
        uses: actions/download-artifact@v4
        with:
          name: ossasai-audit-results

      - name: Generate weekly summary
        run: |
          echo "============================================"
          echo "OSSASAI Weekly Compliance Report"
          echo "============================================"
          echo "Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo ""

          if [ -f "compliance-report.txt" ]; then
            cat compliance-report.txt
          else
            echo "No compliance report available"
          fi

          # Add notification integration here
          # Examples:
          # - Slack: curl -X POST -H 'Content-type: application/json' --data '...' $SLACK_WEBHOOK_URL
          # - Email: Use a GitHub Action for sending emails
          # - PagerDuty: Create incident if compliance fails
